### Excel spreadsheet to event file to load to Petrel

In [5]:
import pandas as pd

df = pd.read_excel('Perf to event file2.xlsx')



Well_list = ["130_h", "134_h", "136_h", "138_h", "152_h", "157_h" ,"162_h" ,"200_h" ,"201_h" , "202_h",
             "204_h", "205_h" ,"206_h" ,"207_h", "208_h" ,"209_h" ,"211_h" ,"212_h", "213_h", "214_h",
             "216_h", "218_h" , "219_h", "221_h", "223_h", "227_h", "240_h", "4252_h", "4253_h"]

for well in Well_list:
    file_name = well + '.ev'
    with open(file_name, 'w') as file:
        file.write('UNITS METRIC \n \nWELLNAME ')
        file.write("\"" + str(well) + "\"")
        file.write('\n')
    df_well = df[(df['Well'] == well)]
    df_well = df_well.drop(['Well'], axis=1)
    df_well.to_csv(file_name, sep='\t', mode='a+', header=False, index=False)
df.head()

    Well  Perf_Date         Type   Perf_top   Perf_bot      D  A  B  C
0  130_h 2017-10-08  perforation     3141.0     3146.0  0.114  0  0  0
1  130_h 2017-10-08  perforation     3156.0     3161.0  0.114  0  0  0
2  130_h 2017-10-11  perforation     3141.0     3146.0  0.114  0  0  0
3  130_h 2017-10-11  perforation     3156.0     3161.0  0.114  0  0  0
4  130_h 2017-10-13  perforation     3101.0     3108.0  0.114  0  0  0